# Generated by Django 5.0.4 on 2025-01-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
